logging:
  level:
    org.springframework.security: DEBUG

spring:
  main:
      allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/activity-db
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
  port: 8080
  servlet:
    context-path: /activity-api
    session:
      timeout: 10m #session to 10 minutes
